spring:
  datasource:
    url: jdbc:mysql://localhost:3306/root?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 5959@Ssol
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: jwtSecret
UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token
