server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://legossol.crrrqqjyomfc.ap-northeast-2.rds.amazonaws.com:3306/legossol?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    # username: admin
    # password: legossol
    url: jdbc:mysql://localhost:3306/campaign?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 5959@Ssol
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: jwtSecret

UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token
